/**
 * The following code is generated by D&A UI Framework.
 * It is not expected to be modified by developers.
 * Any modification may paralyze the form.!!
 * So we strongly recommend that you do not change any thing of this file.!!
 */
 
 
package com.jiuqi.gmc.mobile.approval.ui.page;

import com.jiuqi.dna.ui.wt.widgets.FormControls;
import com.jiuqi.dna.ui.wt.widgets.Composite;
import com.jiuqi.dna.ui.wt.widgets.Button;
import com.jiuqi.dna.ui.wt.widgets.Label;
import com.jiuqi.dna.ui.wt.widgets.Text;


public class JPushSettingPageControls extends FormControls{
	public Composite cmp_setting;
	public Button chk_push;
	public Label label_1;
	public Label lbl_app_key;
	public Text txt_app_key;
	public Label lbl_master_secret;
	public Text txt_master_key;
	
}